-- 트리거 : 데이터 

CREATE TABLE EMP_TRG
AS SELECT * FROM emp;

-- 트리거 생성
-- RAISE_APPLICATION_ERROR(오류코드번호, '메세지') : 강제 EXCEPTION
CREATE OR REPLACE
TRIGGER TRG_NODML_WEEKEND
BEFORE 
INSERT
	OR
UPDATE
	OR
DELETE
	ON
	EMP_TRG
BEGIN
		IF TO_CHAR(SYSDATE, 'DY') IN ('토', '일') THEN 
	IF INSERTING THEN 
	RAISE_APPLICATION_ERROR(-20000,
		'주말 사원정보 추가 불가');

ELSIF UPDATING THEN
RAISE_APPLICATION_ERROR(-20001,
'주말 사원정보 수정 불가');

ELSIF DELETING THEN
RAISE_APPLICATION_ERROR(-20002,
'주말 사원정보 삭제 불가');
ELSE	
RAISE_APPLICATION_ERROR(-20003,
'주말 사원정보 변경 불가');
END IF;
END IF;
END;

UPDATE EMP_TRG SET SAL = 2700 WHERE EMPNO =7844;
SELECT * FROM EMP_TRG;

CREATE USER c##ja

CREATE TABLE EMP_TRG_LOG(
	TABLENAME VARCHAR2(10), -- DML 이 수행된 테이블 명
	DML_TYPE VARCHAR2(10), -- DML 명령어의 종류
	EMPNO NUMBER(4), -- DML 대상이 된 사원번호
	USER_NAME VARCHAR2(30), -- DML 을 수행한 USER 이름
	CHANGE_DATE DATE -- DML 이 수행된 날짜
);

CREATE OR REPLACE TRIGGER TRG_EMP_LOG
AFTER 
INSERT OR UPDATE OR DELETE ON EMP_TRG
FOR EACH ROW

BEGIN	
	IF INSERTING THEN	
	INSERT INTO	EMP_TRG_LOG
	VALUES('EMP_TRG', 'INSERT', NEW.empno, SYS_CONTEXT('USERENV', 'SESSION_USER'), sysdate);
ELSIF UPDATING THEN
INSERT INTO	EMP_TRG_LOG
	VALUES('EMP_TRG', 'UPDATE', old.empno, SYS_CONTEXT('USERENV', 'SESSION_USER'), sysdate);
ELSIF DELETING THEN
INSERT INTO	EMP_TRG_LOG
	VALUES('EMP_TRG', 'DELETE', old.empno, SYS_CONTEXT('USERENV', 'SESSION_USER'), sysdate);
END IF;
END;


INSERT INTO EMP_TRG
VALUES(9999, 'TESTEMP', 'CLERK', 7788, '2018-02-02', 1200, NULL, 20);

SELECT *FROM EMP_TRG;
SELECT *FROM EMP_TRG_LOG;

-- 트리거 제거
DROP TRIGGER TRG_NODML_WEEKEND;